# Generated by Django 6.0 on 2025-12-25 12:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('enabled', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('latest', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('nps', models.PositiveIntegerField(default=0)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='openrank.enginefamily')),
            ],
        ),
        migrations.CreateModel(
            name='RatingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thread_count', models.IntegerField()),
                ('hashsize', models.IntegerField()),
                ('base_time', models.FloatField()),
                ('increment', models.FloatField()),
                ('engines', models.ManyToManyField(blank=True, related_name='rating_lists', to='openrank.engine')),
            ],
        ),
        migrations.CreateModel(
            name='RatingListStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField()),
                ('top_n_engines', models.PositiveIntegerField()),
                ('games', models.PositiveIntegerField()),
                ('rating_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='openrank.ratinglist')),
            ],
            options={
                'ordering': ['stage_number'],
            },
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LL', models.IntegerField(default=0)),
                ('LD', models.IntegerField(default=0)),
                ('DD', models.IntegerField(default=0)),
                ('DW', models.IntegerField(default=0)),
                ('WW', models.IntegerField(default=0)),
                ('engine_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_a', to='openrank.engine')),
                ('engine_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_b', to='openrank.engine')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='openrank.ratingliststage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='engine',
            constraint=models.UniqueConstraint(condition=models.Q(('latest', True)), fields=('family',), name='unique_latest_engine_per_family'),
        ),
        migrations.AddConstraint(
            model_name='ratingliststage',
            constraint=models.UniqueConstraint(fields=('rating_list', 'stage_number'), name='unique_stage_per_rating_list'),
        ),
    ]
