# Generated by Django 6.0 on 2025-12-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='book_index',
            field=models.IntegerField(default=0),
        ),
    ]
