# Generated by Django 6.0 on 2025-12-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginefamily',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
