# Generated by Django 6.0 on 2025-12-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0002_alter_enginefamily_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
