# Generated by Django 6.0 on 2025-12-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0003_engine_released_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='released_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
