# Generated by Django 6.0 on 2025-12-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0004_worker_delete_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
