# Generated by Django 6.0 on 2025-12-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0004_alter_engine_released_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='released_at',
            new_name='release_date',
        ),
    ]
