# Generated by Django 6.0 on 2025-12-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0005_rename_released_at_engine_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingListStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField()),
                ('top_n_engines', models.PositiveIntegerField()),
                ('game_count', models.PositiveIntegerField()),
                ('rating_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='openrank.ratinglist')),
            ],
            options={
                'ordering': ['stage_number'],
                'constraints': [models.UniqueConstraint(fields=('rating_list', 'stage_number'), name='unique_stage_per_rating_list')],
            },
        ),
    ]
