# Generated by Django 6.0 on 2025-12-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0005_pairing_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinglist',
            name='book',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
