# Generated by Django 6.0 on 2025-12-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0006_ratingliststage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinglist',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
