# Generated by Django 6.0 on 2025-12-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0007_ratinglist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingliststage',
            old_name='game_count',
            new_name='games',
        ),
    ]
