# Generated by Django 6.0 on 2025-12-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0008_rename_game_count_ratingliststage_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engine',
            name='latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='engine',
            constraint=models.UniqueConstraint(condition=models.Q(('latest', True)), fields=('family',), name='unique_latest_engine_per_family'),
        ),
    ]
