# Generated by Django 6.0 on 2025-12-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0009_engine_disabled_engine_latest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
