# Generated by Django 6.0 on 2025-12-22 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0010_engine_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LL', models.IntegerField(default=0)),
                ('LD', models.IntegerField(default=0)),
                ('DD', models.IntegerField(default=0)),
                ('DW', models.IntegerField(default=0)),
                ('WW', models.IntegerField(default=0)),
                ('engine_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_a', to='openrank.engine')),
                ('engine_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_b', to='openrank.engine')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='openrank.ratingliststage')),
            ],
        ),
    ]
