# Generated by Django 6.0 on 2025-12-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0011_pairing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinglist',
            name='base_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ratinglist',
            name='increment',
            field=models.IntegerField(),
        ),
    ]
