# Generated by Django 6.0 on 2025-12-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0012_alter_ratinglist_base_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinglist',
            name='engines',
            field=models.ManyToManyField(blank=True, related_name='rating_lists', to='openrank.engine'),
        ),
    ]
