# Generated by Django 6.0 on 2025-12-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0013_ratinglist_engines'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='nps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
